### ISSUE TITLE
Cannot use Exact-out

### ISSUE THREAD

**Issue by Thanos420NoScope** [kadena-io/kadenaswap#104]
## Expected Behavior
Should sign and send the transaction

## Actual Behavior
The preview says it cant get a response from node and fails

![image](https://user-images.githubusercontent.com/6309193/108662249-effcb100-749b-11eb-9deb-a53ef2f30213.png)

## Steps to Reproduce the Problem

  1. Make an exact-out trade
  2. Try to sign in Chainweaver
  3. Node wont answer

**Comment by ggobugi27** [comment]
Closed #105
