### ISSUE TITLE
NaN% as Slippage Tolerance

### ISSUE THREAD

**Issue by coolio-coder** [kadena-io/kadenaswap#26]
I tried playing around with the Slippage Tolerance percentages but encountered an error in the input form field after entering a decimal after a zero: `0.%`. You can not delete the text and refreshing the page does not resolve the issue.

![Kadenaswap](https://user-images.githubusercontent.com/53714543/103379153-ac488500-4ab2-11eb-8ee4-878abc43bf5c.png)

**Comment by fmelp** [comment]
fixed! thank you @coolio-coder
