### ISSUE TITLE
Password and private Key visible in console after signing with private key

### ISSUE THREAD

**Issue by cryptofirst** [kadena-io/kadenaswap#33]
Password and private Key visible in console after signing with private key

Page name -- "Your KDA account"
select Private key+ password option >> enter private key and password >> hit update

check browser console.

![image](https://user-images.githubusercontent.com/76821037/103420243-4d434880-4b64-11eb-8f40-efba19b18fcd.png)

**Comment by fmelp** [comment]
fixed, thank you!
