### ISSUE TITLE
On click of cancel button on enter password pop up - "Incorrect password. If forgotten, you can reset it with your private key" is shown which is wrong. user didnt enter the password.

### ISSUE THREAD

**Issue by cryptofirst** [kadena-io/kadenaswap#34]
Enter a password on input password field >> click on cancel button

<img width="954" alt="image" src="https://user-images.githubusercontent.com/76821037/103421780-30ab0e80-4b6c-11eb-941d-6d7f79b27f51.png">

**Comment by fmelp** [comment]
thank you!! closed here https://github.com/kadena-io/kadenaswap/pull/47
