### ISSUE TITLE
Nan showing in input field when using special chars for swapping

### ISSUE THREAD

**Issue by cryptofirst** [kadena-io/kadenaswap#36]
![image](https://user-images.githubusercontent.com/76821037/103421994-453bd680-4b6d-11eb-8fc1-b3136eccde22.png)

vice versa

![image](https://user-images.githubusercontent.com/76821037/103422031-74524800-4b6d-11eb-8a0d-a722816284ab.png)

**Comment by fmelp** [comment]
fixed, thanks!
