### ISSUE TITLE
Should there be some restriction on input field digit length?

### ISSUE THREAD

**Issue by cryptofirst** [kadena-io/kadenaswap#37]
there should be some restriction on input field length i.e. swapping 0.0000000000001 KDA to XYZ and TO field shows amount in scientific format and then after clicking on SWAP, error message shows as "Cannot resolve e-13"

Adding a limit will help user to reduce number of steps and repeating the same steps again in order to swap the tokens,

![image](https://user-images.githubusercontent.com/76821037/103422126-d612b200-4b6d-11eb-8d79-bbafe17d3d93.png)

**Comment by sirlensalot** [comment]
Adding @cryptofirst 's comment about precision error, the UI is generating values that are too high-precision:
![image](https://user-images.githubusercontent.com/8353613/103468701-e8394f80-4d29-11eb-8de1-d7e3116cb890.png)
![image](https://user-images.githubusercontent.com/8353613/103468705-0bfc9580-4d2a-11eb-8c7c-db250320ae4d.png)

**Comment by cryptofirst** [comment]
look into the restriction on Remove Liquidity input field... I can enter 0.0000001% and hit remove liquidity button which gives the error

<img width="725" alt="Screen Shot 2021-01-02 at 7 09 47 PM" src="https://user-images.githubusercontent.com/76821037/103469124-bd9dc580-4d2e-11eb-8678-6ef17c040c8c.png">

<img width="661" alt="Screen Shot 2021-01-02 at 7 13 40 PM" src="https://user-images.githubusercontent.com/76821037/103469114-a2cb5100-4d2e-11eb-9754-3daa08e7ea8c.png">
