### ISSUE TITLE
Buttons not displayed properly on Mac Safari browser.

### ISSUE THREAD

**Issue by cryptofirst** [kadena-io/kadenaswap#39]
<img width="818" alt="Screen Shot 2021-01-01 at 8 24 59 PM" src="https://user-images.githubusercontent.com/76821037/103449366-553edd80-4c75-11eb-96aa-166be341c082.png">

**Comment by fmelp** [comment]
Thank you for bringing this up, but we will not support safari. Does not connect to any crypto wallets for other chains (ie metamask)
