### ISSUE TITLE
Duplicate transactions are submitted if user clicks Send transaction button multiple times.

### ISSUE THREAD

**Issue by cryptofirst** [kadena-io/kadenaswap#42]
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/76821037/103449486-df3b7600-4c76-11eb-8c6c-cb553ef553bd.png">

<img width="1243" alt="Screen Shot 2021-01-01 at 8 57 36 PM" src="https://user-images.githubusercontent.com/76821037/103449493-e82c4780-4c76-11eb-9d49-a5c96978e5da.png">

**Comment by fmelp** [comment]
fixed, thanks!
