### ISSUE TITLE
Original signing method state is not retained if user hit Reset and hit cancel button on Account page

### ISSUE THREAD

**Issue by cryptofirst** [kadena-io/kadenaswap#43]
<img width="891" alt="Screen Shot 2021-01-02 at 6 51 09 PM" src="https://user-images.githubusercontent.com/76821037/103469021-8975d500-4d2d-11eb-9796-cc7654cb76ec.png">

<img width="1005" alt="Screen Shot 2021-01-02 at 6 52 32 PM" src="https://user-images.githubusercontent.com/76821037/103469023-8e3a8900-4d2d-11eb-9e70-edafea9cd6a2.png">

<img width="1019" alt="Screen Shot 2021-01-02 at 6 58 58 PM" src="https://user-images.githubusercontent.com/76821037/103469026-92ff3d00-4d2d-11eb-9f75-53b119531c57.png">

**Comment by fmelp** [comment]
resolved, thank you!
