### ISSUE TITLE
Token Balance - Menu implementation

### ISSUE THREAD

**Issue by conr4d86** [kadena-io/kadenaswap#45]
![image](https://user-images.githubusercontent.com/76919710/103489170-b9e36f00-4e12-11eb-835d-fa8a7cda3ae9.png)

**Comment by fmelp** [comment]
alternative is to show account balance next to every token in the selection dropdown (similar to uniswap)

**Comment by fmelp** [comment]
![Screenshot 2021-01-20 at 13 04 23](https://user-images.githubusercontent.com/5041936/105209479-42a32000-5b20-11eb-8a5d-cc75b98d2d32.jpg)
have the balances show up here on the right instead
